### PR TITLE
fix errors in Makefile

### PR DESCRIPTION
**Pull request by pantafive**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by SZubarev** [comment]
Docker compose is now bundled into docker and no need for a separate docker-compose executable to use: https://docs.docker.com/engine/reference/commandline/compose_up/

**Comment by pantafive** [comment]
```
❯ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
❯ docker --version
Docker version 20.10.8, build 3967b7d
```
Ubuntu 21.04

**Review by SZubarev — APPROVED** [review]

**Comment by pantafive** [comment]
Thank you! I'm very happy to contribute to the project!

**Comment by SZubarev** [comment]
Thanks for the contribution!

**Pull request merged**
